### ISSUE TITLE
implement deferred download

### ISSUE THREAD

**Issue by lduboeuf** [ubports/nuntium#1]
Currently, when cellular data is off, the mms wap push notification is received, but the mms get lost and not possible to retrieve it later.
As well, the system might handle user who don't want autoretrieval of the mms ( think of low internet plan, or expensive fee )

There is a TODO in code that talk about it:
https://github.com/ubports/nuntium/blob/xenial/cmd/nuntium/mediator.go#L147-L149

ref issue: https://github.com/ubports/ubuntu-touch/issues/239

**Comment by lduboeuf** [comment]
@sergiusens would you like to work on it ?

**Comment by sergiusens** [comment]
On Fri, 2020-04-03 at 12:56:51 -0300, Lionel Duboeuf wrote:

> @sergiusens would you like/available to work on it ?

Yes I would, mid-May though and only on the nuntium side, we can
implement a signal for Telepathy to capture and hook up the UI to
request the download for later.

Similar for Issue #2

**Comment by lduboeuf** [comment]
@sergiusens that would be awesome, thank you

**Comment by lduboeuf** [comment]
hello @sergiusens , any updates since ?

**Comment by sergiusens** [comment]
I wrote on the master bug https://github.com/ubports/ubuntu-touch/issues/1408 on getting this started.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/nuntium/-/issues/1

Sorry for your inconvenience.
